<?php
// Variables expected:
// $reportTitle, $reportTypeLabel, $generatedBy, $generatedAt, $recordCount,
// $summary, $columns, $rows, $logoDataUri, $footerText
if (empty($columns)) {
  $columns = [
    ['key' => '', 'label' => 'Record']
  ];
}
?>
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: "Times New Roman", Times, serif; font-size: 12px; color: #222; }
    .page { width: 210mm; min-height: 297mm; }
    .header { border-bottom: 2px solid #1f2a44; padding-bottom: 10px; margin-bottom: 10px; }
    .header-table { width: 100%; border-collapse: collapse; }
    .logo-cell { width: 20%; vertical-align: middle; }
    .logo { max-height: 60px; width: auto; display: inline-block; }
    .school-name { text-align: center; font-size: 14px; font-weight: bold; letter-spacing: 0.5px; }
    .school-sub { text-align: center; font-size: 11px; color: #444; }
    .report-title { text-align: center; font-size: 18px; font-weight: bold; margin: 14px 0 6px; text-transform: uppercase; }
    .divider { border-top: 1px solid #1f2a44; margin: 10px 0; }
    .meta { margin: 8px 0 12px; }
    .meta-row { display: flex; justify-content: space-between; margin-bottom: 4px; }
    .meta-label { font-weight: bold; color: #111; min-width: 120px; display: inline-block; }
    .section-title { font-weight: bold; margin: 12px 0 6px; font-size: 13px; }
    .summary-list { margin: 0; padding-left: 16px; }
    .summary-list li { margin-bottom: 4px; }
    .table { width: 100%; border-collapse: collapse; margin-top: 6px; font-size: 11px; }
    .table th { background: #f0f2f6; border: 1px solid #d0d6e2; padding: 6px; text-align: left; }
    .table td { border: 1px solid #d0d6e2; padding: 6px; vertical-align: top; }
    .footer { margin-top: 14px; border-top: 1px solid #c7ceda; padding-top: 6px; font-size: 10px; text-align: center; color: #666; }
  </style>
</head>
<body>
  <div class="page">
    <div class="header">
      <table class="header-table">
        <tr>
          <td class="logo-cell">
            <?php if (!empty($logoDataUri)) { ?>
              <img src="<?php echo htmlspecialchars($logoDataUri); ?>" alt="MCA Logo" class="logo" />
            <?php } else { ?>
              <div style="font-weight:bold; font-size:12px;">MCA</div>
            <?php } ?>
          </td>
          <td>
            <div class="school-name">Maranatha Christian Academy Foundation</div>
            <div class="school-sub">Calapan City, Inc.</div>
            <div class="school-sub">Official Administrative Report</div>
          </td>
          <td class="logo-cell"></td>
        </tr>
      </table>
    </div>

    <div class="report-title"><?php echo htmlspecialchars(strtoupper($reportTitle)); ?></div>
    <div class="divider"></div>

    <div class="meta">
      <div class="meta-row"><span class="meta-label">Generated by:</span> <span><?php echo htmlspecialchars($generatedBy); ?></span></div>
      <div class="meta-row"><span class="meta-label">Generated at:</span> <span><?php echo htmlspecialchars($generatedAt); ?></span></div>
      <div class="meta-row"><span class="meta-label">Report Type:</span> <span><?php echo htmlspecialchars($reportTypeLabel); ?></span></div>
      <div class="meta-row"><span class="meta-label">Record Count:</span> <span><?php echo htmlspecialchars((string)$recordCount); ?></span></div>
    </div>

    <div class="section-title">I. Report Summary</div>
    <ul class="summary-list">
      <?php foreach ($summary as $item) { 
        $label = $item['label'] ?? '';
        $value = $item['value'] ?? '';
      ?>
        <li><strong><?php echo htmlspecialchars((string)$label); ?>:</strong> <?php echo htmlspecialchars(report_value_to_string($value)); ?></li>
      <?php } ?>
    </ul>

    <div class="section-title">II. Detailed Records</div>
    <table class="table">
      <thead>
        <tr>
          <?php foreach ($columns as $col) { ?>
            <th><?php echo htmlspecialchars((string)($col['label'] ?? '')); ?></th>
          <?php } ?>
        </tr>
      </thead>
      <tbody>
        <?php if (empty($rows)) { ?>
          <tr><td colspan="<?php echo count($columns); ?>">No records available.</td></tr>
        <?php } else { ?>
          <?php foreach ($rows as $row) { ?>
            <tr>
              <?php foreach ($columns as $col) { 
                $key = $col['key'] ?? '';
                $value = is_array($row) && $key !== '' && array_key_exists($key, $row) ? $row[$key] : '';
              ?>
                <td><?php echo htmlspecialchars(report_value_to_string($value)); ?></td>
              <?php } ?>
            </tr>
          <?php } ?>
        <?php } ?>
      </tbody>
    </table>

    <div class="footer">
      <?php echo htmlspecialchars($footerText); ?> - Generated <?php echo htmlspecialchars($generatedAt); ?>
    </div>
  </div>
</body>
</html>
